env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - prettier
settings:
  react:
    version: detect
rules:
  react/prop-types: [ 0 ]
  sort-imports: [ "error", {
    "ignoreCase": true,
    "ignoreDeclarationSort": false,
    "ignoreMemberSort": false,
    "memberSyntaxSortOrder": [ "none", "all", "multiple", "single" ],
    "allowSeparatedGroups": false
  } ]
